### ISSUE TITLE
Bower Deps Order

### ISSUE THREAD

**Issue by osdevisnot** [joliss/broccoli-bower#12]
With jquery and angular as bower deps, `bowerFiles()` returns deps in incorrect order. This causes angular to use jqLite instead of jquery.

The problem is highlighted in repo here: https://github.com/abhishekisnot/broccoli-bower-demo

After cloning that repo, run `npm install` and `npm run-script postinstall` and check public/scripts/vendor.js

I think, broccoli-bower should look at bower.json to figure out deps order.

**Comment by ankeetmaini** [comment]
Is there any workaround currently? It fails with bootstrap. jQuery is added to the concatenated file later.

**Comment by ankeetmaini** [comment]
I managed to get this working by giving the order in concat plugin like this

```
var javascripts = concat(dependencyTree, {
inputFiles: ['**/jquery.js', '**/*.js'],
outputFile: '/assets/app.js'
});
```

This makes sure, the jquery library is always added first.

**Comment by joliss** [comment]
I'm not maintaining this repo at the moment; I recommend avoiding it and manually wiring up your `bower_components/foo/lib`-type paths.
