### ISSUE TITLE
problem when vendor's bower.json repeats file names

### ISSUE THREAD

**Issue by ballPointPenguin** [joliss/broccoli-bower#4]
commit [328973b] to twbs/bootstrap-sass adds a verbose main: [] arrary to its bower.json.
This causes ember-cli build step to break with "EEXIST, file already exists 'tmp/main_file_picker-tmp_dest_dir-***.tmp/_alerts.scss'Error: EEXIST"

I haven't dug in too deeply, but it seems to be an issue of multiple files in this array having the same file name ('_alerts.scss' in this case).

I am not sure if the bower spec has anything to say about this. I am also not sure if the appropriate fix should be on broccoli-bower, bootstrap-sass, my app.scss file, my Brocfile, ember-cli, the bower spec, or somewheres else.

see https://github.com/twbs/bootstrap-sass/pull/586

**Comment by ef4** [comment]
I just confirmed your guess. The collision is definitely happening when broccoli tries to write 

```
vendor/assets/stylesheets/bootstrap/mixins/_alerts.scss
```

on top of

```
vendor/assets/stylesheets/bootstrap/_alerts.scss
```

**Comment by ef4** [comment]
`basename` here causes the collision:

https://github.com/joliss/broccoli-bower/blob/master/index.js#L32
